import { Exercise } from '../types';

export const DEFAULT_EXERCISES: Exercise[] = [
  { id: 'e1', name: 'Bench Press', muscleGroup: 'chest', category: 'compound' },
  { id: 'e2', name: 'Incline Bench Press', muscleGroup: 'chest', category: 'compound' },
  { id: 'e3', name: 'Cable Fly', muscleGroup: 'chest', category: 'isolation' },
  { id: 'e4', name: 'Push-up', muscleGroup: 'chest', category: 'bodyweight' },
  { id: 'e5', name: 'Dumbbell Fly', muscleGroup: 'chest', category: 'isolation' },
  { id: 'e6', name: 'Decline Bench Press', muscleGroup: 'chest', category: 'compound' },
  { id: 'e7', name: 'Deadlift', muscleGroup: 'back', category: 'compound' },
  { id: 'e8', name: 'Pull-up', muscleGroup: 'back', category: 'bodyweight' },
  { id: 'e9', name: 'Barbell Row', muscleGroup: 'back', category: 'compound' },
  { id: 'e10', name: 'Lat Pulldown', muscleGroup: 'back', category: 'compound' },
  { id: 'e11', name: 'Seated Cable Row', muscleGroup: 'back', category: 'isolation' },
  { id: 'e12', name: 'T-Bar Row', muscleGroup: 'back', category: 'compound' },
  { id: 'e13', name: 'Face Pull', muscleGroup: 'back', category: 'isolation' },
  { id: 'e14', name: 'Overhead Press', muscleGroup: 'shoulders', category: 'compound' },
  { id: 'e15', name: 'Lateral Raise', muscleGroup: 'shoulders', category: 'isolation' },
  { id: 'e16', name: 'Front Raise', muscleGroup: 'shoulders', category: 'isolation' },
  { id: 'e17', name: 'Arnold Press', muscleGroup: 'shoulders', category: 'compound' },
  { id: 'e18', name: 'Rear Delt Fly', muscleGroup: 'shoulders', category: 'isolation' },
  { id: 'e19', name: 'Barbell Curl', muscleGroup: 'biceps', category: 'isolation' },
  { id: 'e20', name: 'Dumbbell Curl', muscleGroup: 'biceps', category: 'isolation' },
  { id: 'e21', name: 'Hammer Curl', muscleGroup: 'biceps', category: 'isolation' },
  { id: 'e22', name: 'Preacher Curl', muscleGroup: 'biceps', category: 'isolation' },
  { id: 'e23', name: 'Tricep Pushdown', muscleGroup: 'triceps', category: 'isolation' },
  { id: 'e24', name: 'Skull Crusher', muscleGroup: 'triceps', category: 'isolation' },
  { id: 'e25', name: 'Overhead Tricep Extension', muscleGroup: 'triceps', category: 'isolation' },
  { id: 'e26', name: 'Close-Grip Bench', muscleGroup: 'triceps', category: 'compound' },
  { id: 'e27', name: 'Squat', muscleGroup: 'legs', category: 'compound' },
  { id: 'e28', name: 'Leg Press', muscleGroup: 'legs', category: 'compound' },
  { id: 'e29', name: 'Romanian Deadlift', muscleGroup: 'legs', category: 'compound' },
  { id: 'e30', name: 'Leg Extension', muscleGroup: 'legs', category: 'isolation' },
  { id: 'e31', name: 'Leg Curl', muscleGroup: 'legs', category: 'isolation' },
  { id: 'e32', name: 'Calf Raise', muscleGroup: 'legs', category: 'isolation' },
  { id: 'e33', name: 'Bulgarian Split Squat', muscleGroup: 'legs', category: 'compound' },
  { id: 'e34', name: 'Hack Squat', muscleGroup: 'legs', category: 'compound' },
  { id: 'e35', name: 'Hip Thrust', muscleGroup: 'glutes', category: 'compound' },
  { id: 'e36', name: 'Glute Kickback', muscleGroup: 'glutes', category: 'isolation' },
  { id: 'e37', name: 'Sumo Deadlift', muscleGroup: 'glutes', category: 'compound' },
  { id: 'e38', name: 'Plank', muscleGroup: 'core', category: 'bodyweight' },
  { id: 'e39', name: 'Cable Crunch', muscleGroup: 'core', category: 'isolation' },
  { id: 'e40', name: 'Hanging Leg Raise', muscleGroup: 'core', category: 'bodyweight' },
];

export const SAMPLE_WORKOUT_PLANS = [
  {
    id: 'wp1', name: 'Push Day', type: 'push', color: '#3D7BFF',
    scheduledDays: [1, 4],
    exercises: [
      { exerciseId: 'e1', exercise: DEFAULT_EXERCISES[0], order: 0, restSeconds: 120, sets: [{ reps: 8, weight: 80, weightUnit: 'kg' }, { reps: 8, weight: 80, weightUnit: 'kg' }, { reps: 8, weight: 80, weightUnit: 'kg' }, { reps: 8, weight: 80, weightUnit: 'kg' }] },
      { exerciseId: 'e14', exercise: DEFAULT_EXERCISES[13], order: 1, restSeconds: 90, sets: [{ reps: 10, weight: 50, weightUnit: 'kg' }, { reps: 10, weight: 50, weightUnit: 'kg' }, { reps: 10, weight: 50, weightUnit: 'kg' }] },
      { exerciseId: 'e15', exercise: DEFAULT_EXERCISES[14], order: 2, restSeconds: 60, sets: [{ reps: 15, weight: 12, weightUnit: 'kg' }, { reps: 15, weight: 12, weightUnit: 'kg' }, { reps: 15, weight: 12, weightUnit: 'kg' }] },
      { exerciseId: 'e23', exercise: DEFAULT_EXERCISES[22], order: 3, restSeconds: 60, sets: [{ reps: 12, weight: 35, weightUnit: 'kg' }, { reps: 12, weight: 35, weightUnit: 'kg' }, { reps: 12, weight: 35, weightUnit: 'kg' }] },
    ],
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: 'wp2', name: 'Pull Day', type: 'pull', color: '#8B5CF6',
    scheduledDays: [2, 5],
    exercises: [
      { exerciseId: 'e7', exercise: DEFAULT_EXERCISES[6], order: 0, restSeconds: 180, sets: [{ reps: 5, weight: 120, weightUnit: 'kg' }, { reps: 5, weight: 120, weightUnit: 'kg' }, { reps: 5, weight: 120, weightUnit: 'kg' }] },
      { exerciseId: 'e10', exercise: DEFAULT_EXERCISES[9], order: 1, restSeconds: 90, sets: [{ reps: 10, weight: 60, weightUnit: 'kg' }, { reps: 10, weight: 60, weightUnit: 'kg' }, { reps: 10, weight: 60, weightUnit: 'kg' }, { reps: 10, weight: 60, weightUnit: 'kg' }] },
      { exerciseId: 'e19', exercise: DEFAULT_EXERCISES[18], order: 2, restSeconds: 60, sets: [{ reps: 12, weight: 30, weightUnit: 'kg' }, { reps: 12, weight: 30, weightUnit: 'kg' }, { reps: 12, weight: 30, weightUnit: 'kg' }] },
    ],
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: 'wp3', name: 'Leg Day', type: 'legs', color: '#10B981',
    scheduledDays: [3, 6],
    exercises: [
      { exerciseId: 'e27', exercise: DEFAULT_EXERCISES[26], order: 0, restSeconds: 180, sets: [{ reps: 5, weight: 100, weightUnit: 'kg' }, { reps: 5, weight: 100, weightUnit: 'kg' }, { reps: 5, weight: 100, weightUnit: 'kg' }, { reps: 5, weight: 100, weightUnit: 'kg' }] },
      { exerciseId: 'e29', exercise: DEFAULT_EXERCISES[28], order: 1, restSeconds: 120, sets: [{ reps: 10, weight: 70, weightUnit: 'kg' }, { reps: 10, weight: 70, weightUnit: 'kg' }, { reps: 10, weight: 70, weightUnit: 'kg' }] },
      { exerciseId: 'e30', exercise: DEFAULT_EXERCISES[29], order: 2, restSeconds: 60, sets: [{ reps: 15, weight: 50, weightUnit: 'kg' }, { reps: 15, weight: 50, weightUnit: 'kg' }, { reps: 15, weight: 50, weightUnit: 'kg' }] },
      { exerciseId: 'e32', exercise: DEFAULT_EXERCISES[31], order: 3, restSeconds: 60, sets: [{ reps: 20, weight: 60, weightUnit: 'kg' }, { reps: 20, weight: 60, weightUnit: 'kg' }, { reps: 20, weight: 60, weightUnit: 'kg' }] },
    ],
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
];